sudo: false
language: python
notifications:
  slack:
    secure: gQl8hvzCWJrjdjytO7jvtJDn4pKHxqDsrSFXNcNXj2A0WJzSh2UKJ4aCBWaSyaMBxHxy8rHZnSgKAQjynILRM6GtMGt0qpRTHNDRCLYW3AeDuZob5tCQPamiNj1PoQK59GhbNDUZdpQkiZ1qVzskBLkCfDG0z7U5KMMuBcHNO+g=
cache:
  directories:
  - ${HOME}/.cache/pip
matrix:
  include:
  - os: linux
    python: 2.7
  - os: osx
    language: generic
before_install:
- echo "HOME="
- echo $HOME
install:
- yes | ./install_sct
- source $HOME/build/neuropoly/spinalcordtoolbox/bin/sct_launcher
- echo $PATH
script:
- sct_testing -d 1
- echo "DONE"
